### ISSUE TITLE
Satellite not proxying

### ISSUE THREAD

**Issue by 0x57696c6c** [t94j0/satellite#21]
proxy.yml:
`- path: /a`
`proxy: http://192.168.0.100`

a.info:
`serve: 10`

Cobalt Strike payload is at:
http://192.168.0.100/a

Issue: Satellite doesn't seem to be picking up the proxy.yml file in the webroot and is simply displaying a 404 error when visiting https://\<satelitte URL\>/a

**Comment by eddiezab** [comment]
Apparently, documentation is incorrect... I appears if you create the file as `.proxy.yml` it works as expected.
