### ISSUE TITLE
Proxy - URI globbing

### ISSUE THREAD

**Issue by khast3x** [t94j0/satellite#22]
Hello,

Thank you for sharing your project!  

I am having issues using Satellite as a proxy for the meterpreter handler. Does the `proxy.yml` file handle path globbing (/myhandlerpath/*) ?
I can set effectively use Satellite to forward the payload, but does not seem to redirect traffic, even with a prefix URI in the handler and the `proxy.yml` file.
If the client is using the URI to send data back to the handler, how can I ensure the traffic is still sent to the handler? 
Best regards,

**Comment by t94j0** [comment]
No, it doesn't do URI globbing but I can add this as a feature request. Thanks for the recommendation!

Make sure the configuration is set up like the [example](https://github.com/t94j0/satellite/blob/master/examples/proxy/proxy.yml). If you're still having issues, post your configuration and I can try to debug it with you.
